In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("creditcard.csv")

In [3]:
df.head

<bound method NDFrame.head of             Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.

In [4]:
df.shape

(284807, 31)

In [6]:
df.info

<bound method DataFrame.info of             Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  

In [8]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [13]:
X = df.drop('Class',axis=1)
y = df['Class']

In [10]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [11]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [12]:
df.dtypes

Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
Class       int64
dtype: object

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42,stratify=y)


In [16]:
X_train.shape,X_test.shape

((213605, 30), (71202, 30))

In [17]:
from sklearn.preprocessing import StandardScaler
Scaler = StandardScaler()
X_train = Scaler.fit_transform(X_train)
X_test = Scaler.transform(X_test)


In [18]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=100)
model.fit(X_train,y_train)


LogisticRegression()

In [19]:
y_pred = model.predict(X_test)

In [24]:
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_test,y_pred)
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00     71079\n           1       0.85      0.63      0.72       123\n\n    accuracy                           1.00     71202\n   macro avg       0.92      0.81      0.86     71202\nweighted avg       1.00      1.00      1.00     71202\n'

In [26]:
y_prob = model.predict_proba(X_test)

In [27]:
y_prob[:5]

array([[1.00000000e+00, 1.55459399e-10],
       [9.98115475e-01, 1.88452512e-03],
       [9.99181535e-01, 8.18465148e-04],
       [9.98835273e-01, 1.16472697e-03],
       [9.99892142e-01, 1.07858087e-04]])

In [28]:
y_pred_default = (y_prob[:,1]>=0.5).astype(int)

In [30]:
confusion_matrix(y_test,y_pred_default)
classification_report(y_test,y_pred_default)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00     71079\n           1       0.85      0.63      0.72       123\n\n    accuracy                           1.00     71202\n   macro avg       0.92      0.81      0.86     71202\nweighted avg       1.00      1.00      1.00     71202\n'

In [34]:
threshold = 0.3
y_pred_custom = (y_prob[:,1] >= threshold).astype(int)
fraud_prob = model.predict_proba(X_test)[:,1]

In [35]:
from sklearn.metrics import precision_score,recall_score
thresholds = [0.9,0.7,0.5,0.3,0.1]
for t in thresholds:
    y_pred_t = (fraud_prob >= t).astype(int)
    precision = precision_score(y_test,y_pred_t)
    recall = recall_score(y_test,y_pred_t)
    print(f"threshold:{t}")
    print(f"precision:{precision:.3f}")
    print(f"recall:{recall:.3f}")
    print("-"*30)
    

threshold:0.9
precision:0.831
recall:0.480
------------------------------
threshold:0.7
precision:0.851
recall:0.602
------------------------------
threshold:0.5
precision:0.846
recall:0.626
------------------------------
threshold:0.3
precision:0.764
recall:0.683
------------------------------
threshold:0.1
precision:0.717
recall:0.740
------------------------------


In [38]:
from sklearn.metrics import confusion_matrix,classification_report
threshold = 0.3
y_pred_03 = (fraud_prob >= threshold).astype(int)
print(confusion_matrix(y_test,y_pred_03))
print(classification_report(y_test,y_pred_03))      

[[71053    26]
 [   39    84]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     71079
           1       0.76      0.68      0.72       123

    accuracy                           1.00     71202
   macro avg       0.88      0.84      0.86     71202
weighted avg       1.00      1.00      1.00     71202



In [42]:
from sklearn.linear_model import LogisticRegression

model_bal = LogisticRegression(
    max_iter=1000,
    class_weight='balanced'
)

model_bal.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [43]:
fraud_prob_bal = model_bal.predict_proba(X_test)[:,1]

In [44]:
from sklearn.metrics import confusion_matrix, classification_report

y_pred_bal = (fraud_prob_bal >= 0.5).astype(int)

print(confusion_matrix(y_test, y_pred_bal))
print(classification_report(y_test, y_pred_bal))

[[69444  1635]
 [   14   109]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99     71079
           1       0.06      0.89      0.12       123

    accuracy                           0.98     71202
   macro avg       0.53      0.93      0.55     71202
weighted avg       1.00      0.98      0.99     71202



In [46]:
threshold = 0.3
y_pred_bal_03 = (fraud_prob_bal >= threshold).astype(int)

print(confusion_matrix(y_test, y_pred_bal_03))
print(classification_report(y_test, y_pred_bal_03))

[[67328  3751]
 [   12   111]]
              precision    recall  f1-score   support

           0       1.00      0.95      0.97     71079
           1       0.03      0.90      0.06       123

    accuracy                           0.95     71202
   macro avg       0.51      0.92      0.51     71202
weighted avg       1.00      0.95      0.97     71202



In [47]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight='balanced',
    n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_jobs=-1, random_state=42)

In [48]:
fraud_prob_rf = rf.predict_proba(X_test)[:, 1]

In [49]:
from sklearn.metrics import confusion_matrix, classification_report

y_pred_rf_05 = (fraud_prob_rf >= 0.5).astype(int)

print(confusion_matrix(y_test, y_pred_rf_05))
print(classification_report(y_test, y_pred_rf_05))

[[71076     3]
 [   34    89]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     71079
           1       0.97      0.72      0.83       123

    accuracy                           1.00     71202
   macro avg       0.98      0.86      0.91     71202
weighted avg       1.00      1.00      1.00     71202



In [50]:
threshold = 0.3
y_pred_rf_03 = (fraud_prob_rf >= threshold).astype(int)

print(confusion_matrix(y_test, y_pred_rf_03))
print(classification_report(y_test, y_pred_rf_03))

[[71071     8]
 [   25    98]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     71079
           1       0.92      0.80      0.86       123

    accuracy                           1.00     71202
   macro avg       0.96      0.90      0.93     71202
weighted avg       1.00      1.00      1.00     71202

